app.s3.bucket=${AWS_S3_BUCKET_NAME:dummy-bucket}
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:dummy}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:dummy}
cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
cloud.aws.region.auto=false
cloud.aws.stack.auto=false

# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB