services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
      MYSQL_DATABASE: Groomhim
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
    name: mysql-data
    driver: local
