spring.config.import=\
    classpath:properties/dev/database.properties, \
    classpath:properties/dev/web.properties, \
    classpath:properties/dev/auth.properties, \
    classpath:properties/dev/cloud.properties