# datasource
spring.datasource.url=${RDB_URL}
spring.datasource.username=${RDB_USERNAME}
spring.datasource.password=${RDB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# OSIV
spring.jpa.open-in-view=false
