CREATE TABLE BRAND
(
    BRAND_ID    BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_EN_NM VARCHAR(255),
    BRAND_NM    VARCHAR(255),
    PRIMARY KEY (BRAND_ID)
);

CREATE TABLE CATEGORY
(
    CATEGORY_ID       VARCHAR(255) NOT NULL,
    CATEGORY_NM       VARCHAR(255),
    CATEGORY_TYPE     VARCHAR(255),
    DEPTH             INT,
    IS_LEAF           BIT,
    UPPER_CATEGORY_ID VARCHAR(255),
    PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID       BIGINT NOT NULL AUTO_INCREMENT,
    DISCOUNT_RATE    DOUBLE PRECISION,
    DISCOUNTED_PRICE DECIMAL(19, 2),
    PRICE            DECIMAL(19, 2),
    PRODUCT_NAME     VARCHAR(255),
    SKIN_TYPE        VARCHAR(255),
    BRAND_ID         BIGINT,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND (BRAND_ID)
);

CREATE TABLE PRODUCT_IMG
(
    PRODUCT_IMG_ID BIGINT NOT NULL AUTO_INCREMENT,
    IMG_URL        VARCHAR(255),
    PRODUCT_ID     BIGINT,
    PRIMARY KEY (PRODUCT_IMG_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);